"use client";

import { useEffect, useState, type FormEvent } from "react";

type DeliveryPolicy = { serviceArea: string; sameDayCutoff: string; deliveryWindow: string; noticeKa: string; noticeEn: string; noticeRu: string };
type SettingsPayload = { policy: DeliveryPolicy; revision: number; updatedAt: string | null; events: Array<{ id: number; revision: number; actorUserId: number | null; createdAt: string }> };

export function DeliverySettingsWorkspace() {
  const [data, setData] = useState<SettingsPayload | null>(null);
  const [draft, setDraft] = useState<DeliveryPolicy | null>(null);
  const [saving, setSaving] = useState(false);
  const [notice, setNotice] = useState<string | null>(null);
  useEffect(() => { fetch("/api/admin/settings/delivery-policy", { cache: "no-store" }).then((response) => response.ok ? response.json() : null).then((payload) => { if (payload?.policy) { setData(payload); setDraft(payload.policy); } }).catch(() => setNotice("პარამეტრების ჩატვირთვა ვერ მოხერხდა.")); }, []);
  const update = <K extends keyof DeliveryPolicy>(key: K, value: DeliveryPolicy[K]) => setDraft((current) => current ? { ...current, [key]: value } : current);
  async function save(event: FormEvent) {
    event.preventDefault(); if (!data || !draft || saving) return; setSaving(true); setNotice(null);
    const response = await fetch("/api/admin/settings/delivery-policy", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ policy: draft, revision: data.revision }) });
    const payload = await response.json().catch(() => null); setSaving(false);
    if (response.ok && payload?.policy) { setData(payload); setDraft(payload.policy); setNotice("მიწოდების პოლიტიკა შენახულია და storefront-ზე უკვე აქტიურია."); }
    else if (response.status === 409) { setNotice("ამ პარამეტრებს სხვა მენეჯერი შეეხო. გვერდი განაახლეთ და სცადეთ ხელახლა."); }
    else setNotice("პარამეტრების შენახვა ვერ მოხერხდა. ველები გადაამოწმეთ.");
  }
  if (!draft) return <div className="pt-7"><div className="h-52 animate-pulse rounded-[var(--radius-lg)] bg-[var(--surface)]" /></div>;
  return <section className="pt-7"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="mono text-[10px] font-bold uppercase tracking-[0.14em] text-[var(--muted)]">Storefront policy</p><h2 className="mt-2 font-display text-[30px] leading-none">მიწოდების პარამეტრები</h2><p className="mt-2 max-w-2xl text-sm text-[var(--muted)]">ეს ტექსტი Checkout-ში customer-facing delivery copy-ს მართავს. თანხები და order calculation ცალკე დაცული წესით ინახება.</p></div><span className="rounded-full bg-[var(--green-soft)] px-3 py-1.5 text-[11px] font-bold text-[var(--green)]">revision {data?.revision ?? 0}</span></div>{notice ? <p role="status" className="mt-5 rounded-[var(--radius)] bg-[var(--surface-sand)] px-4 py-3 text-[12.5px] text-[var(--muted)]">{notice}</p> : null}<form onSubmit={save} className="mt-5 grid gap-5 xl:grid-cols-[minmax(0,1fr)_300px]"><div className="grid gap-4 rounded-[var(--radius-lg)] border border-[var(--line)] bg-[var(--surface)] p-5 shadow-[var(--shadow-card)]"><div className="grid gap-4 sm:grid-cols-3"><Field label="მიწოდების ზონა" value={draft.serviceArea} onChange={(value) => update("serviceArea", value)} /><Field label="იმავე დღის cutoff" type="time" value={draft.sameDayCutoff} onChange={(value) => update("sameDayCutoff", value)} /><Field label="სავარაუდო დრო" value={draft.deliveryWindow} onChange={(value) => update("deliveryWindow", value)} /></div><TextArea label="ქართული ტექსტი" value={draft.noticeKa} onChange={(value) => update("noticeKa", value)} /><TextArea label="English copy" value={draft.noticeEn} onChange={(value) => update("noticeEn", value)} /><TextArea label="Русский текст" value={draft.noticeRu} onChange={(value) => update("noticeRu", value)} /><button type="submit" disabled={saving} className="min-h-11 w-fit rounded-[var(--radius)] bg-[var(--ink)] px-4 text-[13px] font-semibold text-white transition active:scale-[0.97] disabled:opacity-60">{saving ? "ინახება…" : "პარამეტრების შენახვა"}</button></div><aside className="rounded-[var(--radius-lg)] border border-[var(--line)] bg-[var(--surface)] p-5 shadow-[var(--shadow-card)]"><h3 className="font-semibold">ცვლილებების ისტორია</h3><p className="mt-1 text-[12px] leading-relaxed text-[var(--muted)]">ყველა შენახვა ინახება revision-ით. customer-facing ტექსტი აქედან იღებს მონაცემს.</p><ol className="mt-5 grid gap-3">{data?.events?.length ? data.events.map((event) => <li key={event.id} className="border-l-2 border-[var(--green)] pl-3"><p className="text-[12px] font-semibold">revision {event.revision}</p><p className="mt-1 text-[11px] text-[var(--muted)]">{new Date(event.createdAt).toLocaleString("ka-GE")}</p></li>) : <li className="rounded-[var(--radius)] bg-[var(--surface-sand)] p-3 text-[12px] text-[var(--muted)]">პირველი შენახვის შემდეგ ცვლილებების ისტორია აქ გამოჩნდება.</li>}</ol></aside></form></section>;
}

function Field({ label, value, onChange, type = "text" }: { label: string; value: string; onChange: (value: string) => void; type?: string }) { return <label className="grid gap-1.5 text-[12px] font-semibold">{label}<input type={type} value={value} onChange={(event) => onChange(event.target.value)} className="min-h-11 rounded-[var(--radius)] border border-[var(--line)] bg-[var(--surface-warm)] px-3 text-[14px] font-normal outline-none focus:border-[var(--green)]" /></label>; }
function TextArea({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="grid gap-1.5 text-[12px] font-semibold">{label}<textarea rows={3} value={value} onChange={(event) => onChange(event.target.value)} className="min-h-24 rounded-[var(--radius)] border border-[var(--line)] bg-[var(--surface-warm)] px-3 py-2 text-[14px] font-normal outline-none focus:border-[var(--green)]" /></label>; }
